services:
  - type: web
    name: TrafficGenerator
    env: python
    rootDir: backend/app
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      FLASK_APP=app.main flask run --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://trafficgenerator-1.onrender.com
        
  - type: web
    name: traffic-generator-frontend
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        value: https://trafficgenerator-hz4s.onrender.com