services:
  - type: web
    name: traffic-generator-api
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://traffic-generator-frontend.onrender.com

  - type: web
    name: traffic-generator-frontend
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      npm install -g serve
      serve -s dist --listen tcp://0.0.0.0:$PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        value: https://traffic-generator-api.onrender.com 